name: Android CI

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**/*.md'
      - '.clang-format'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - version: v111
            task-name: assembleV111Release
          - version: v115
            task-name: assembleV115Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout assets
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ASSETS_REPO }}
          path: app/src/main/assets
          token: ${{ secrets.ASSETS_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Decode keystore
        env:
          KEYSTORE_ENCODED: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_ENCODED" | base64 -d > app/keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew ${{ matrix.task-name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PvZ-TV-${{ matrix.version }}-release
          path: app/build/outputs/apk/${{ matrix.version }}/release/*.apk

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: >
      github.ref == 'refs/heads/main' &&
      github.repository == 'Dicot0721/PlantsVsZombies-AndroidTV'

    steps:
      - name: Download v111 artifact
        uses: actions/download-artifact@v4
        with:
          name: PvZ-TV-v111-release
          path: apks

      - name: Download v115 artifact
        uses: actions/download-artifact@v4
        with:
          name: PvZ-TV-v115-release
          path: apks

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: continous
          prerelease: true
          title: Automatic CI builds
          files: apks/*.apk
